apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-backend-ingress
  namespace: python-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: "app.student9.devops9.test-danit.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-backend-service
            port:
              number: 80
  tls:
  - hosts:
    - app.student9.devops9.test-danit.com
    secretName: python-app-tls
