apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
  namespace: python-app
spec:
  selector:
    app: python-backend
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
